# Generated by Django 4.2.2 on 2023-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_description',
            field=models.CharField(max_length=300),
        ),
    ]
