# Generated by Django 4.2.2 on 2023-06-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_description',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_master.room')),
            ],
        ),
    ]
