# Generated by Django 4.2.2 on 2023-06-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_master', '0002_alter_room_room_description_notification'),
        ('game_master', '0002_room_image_alter_room_room_description'),
    ]

    operations = [
    ]
