# Generated by Django 4.2.2 on 2023-06-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_master', '0003_merge_20230619_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
