version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./Escape_IT:/Escape_IT
      - ./static:/static
    command: python manage.py runserver 0.0.0.0:8000
