version: '3.9'

services:
  gcloud:
    image: google/cloud-sdk:alpine
    volumes:
      - gcp-creds:/creds
      - .:/Escape_IT
    working_dir: /Escape_IT
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds:
